PracticalCourses/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PracticalCourses.Controllers
{
    public class BasketController : Controller
    {
        public IActionResult AddToBasket(string id)
        {
            return View();
        }
    }
}

PracticalCourses/Controllers/CourseController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PracticalCourses.Interfaces;
using PracticalCourses.Models;

namespace PracticalCourses.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly ICourseService _courseService;

        public CourseController(ICategoryService categoryService, ICourseService courseService)
        {
            _categoryService = categoryService;
            _courseService = courseService;
        }
        
        [HttpGet]
        [Route("Kategoria/{nameCategory}")]
        public IActionResult List(string nameCategory)
        {
            ViewBag.NameCategory = nameCategory;

            return View();
        }
        
        [HttpGet]
        [Route("kurs-{courseId}.html")]
        public IActionResult Details(int courseId)
        {
            return View(AutoMapper.Mapper.Map<CourseResponse>(_courseService.GetById(courseId)));
        }
    }
}

PracticalCourses/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using PracticalCourses.Infrastructure;
using PracticalCourses.Interfaces;
using PracticalCourses.Models;
using PracticalCourses.ViewModel;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PracticalCourses.Controllers
{
    public class HomeController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly ICourseService _courseService;
        private readonly IMemoryCache _cache;

        public HomeController(ICategoryService categoryService, ICourseService courseService, IMemoryCache cache)
        {
            _categoryService = categoryService;
            _courseService = courseService;
            _cache = cache;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {

            List<CategoryResponse> categories = await await _cache.GetOrCreateAsync(Consts.categoriesCacheKey,  entry =>
            {
                entry.SetSlidingExpiration(TimeSpan.FromMinutes(60));
                return Task.FromResult(AutoMapper.Mapper.Map<Task<List<CategoryResponse>>>(_categoryService.GetAllCategory()));
            });

            if (_cache.TryGetValue(Consts.newsCacheKey, out List<CourseResponse> newsCourses))
            {
                newsCourses = _cache.Get(Consts.newsCacheKey) as List<CourseResponse>;
            }
            else
            {
                var cacheEntryOptions = new MemoryCacheEntryOptions()
                    .SetSlidingExpiration(TimeSpan.FromMinutes(60));
                newsCourses = AutoMapper.Mapper.Map<List<CourseResponse>>(_courseService.GetThreeNews());
                _cache.Set(Consts.newsCacheKey, newsCourses, cacheEntryOptions);
            }

            if (_cache.TryGetValue(Consts.bestellersCacheKey, out List<CourseResponse> bestsellersCourses))
            {
                bestsellersCourses = _cache.Get(Consts.bestellersCacheKey) as List<CourseResponse>;
            }
            else
            {
                var cacheEntryOptions = new MemoryCacheEntryOptions()
                    .SetSlidingExpiration(TimeSpan.FromMinutes(60));
                bestsellersCourses = AutoMapper.Mapper.Map<List<CourseResponse>>(_courseService.GetThreeBestsellers());
                _cache.Set(Consts.bestellersCacheKey, bestsellersCourses, cacheEntryOptions);
            }
            
            var vm = new HomeIndexViewModel
            {
                Categories = categories,
                News = newsCourses,
                Bestsellers = bestsellersCourses
            };

            return View(vm);
        }

        public IActionResult SitesStatic(string name)
        {
            return View(name);
        }
    }
}

PracticalCourses/Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "About Us";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AboutUs</h2>

<div>
    Possim vulputate takimata ex tempor consetetur diam duis et eos duo labore dolores voluptua magna vulputate at duo takimata dolore erat accusam
    sed est erat elitr at consetetur augue eleifend diam dolor dolores voluptua nonumy amet takimata et ut amet sea sit dolores feugait adipiscing volutpat 
    magna molestie est dolores takimata te consequat eirmod et justo sadipscing lorem magna nostrud luptatum dolore duis diam sit duis duo sed tempor qui sit lorem 
    at takimata at ad justo vero ut illum clita at diam elit in illum diam sanctus sanctus dolor ipsum nisl dignissim nulla ut te amet amet at eirmod
Amet diam ea ea lorem ipsum magna sea kasd facilisis duis justo gubergren nonumy dolores dolor elitr tempor eum aliquyam ut nonumy volutpat labore ut ipsum ut
    ipsum vero dolor at vero erat dolores dolore nonumy sadipscing ipsum nonummy est ea dolore duo delenit nonumy labore invidunt adipiscing et kasd duo adipiscing 
    lorem volutpat nobis te lorem ad labore dolor et et ipsum sea augue in nulla amet sea clita ipsum dolore facer diam dolore et ut accusam amet dolor eum et sit stet
    duo magna et kasd et hendrerit qui exerci accusam nibh lorem ut vel consetetur sit eos
At et ut labore clita dolor sed no sanctus diam lorem zzril odio dolore vero lorem magna sed sed ut et augue labore lorem dolore suscipit zzril kasd liber 
    elitr voluptua sit accusam eum diam sea et cum ex et diam nobis est eirmod sit lorem diam eirmod aliquyam est eirmod nam et nisl gubergren clita invidunt 
    ut placerat voluptua dolore aliquyam odio ea dolor nonummy dolor sed lorem rebum et dolore nulla et et vel takimata sit lorem facilisi et diam facer nobis laoreet
    eirmod et velit commodo ea at dolore stet at eirmod kasd aliquyam sed tempor takimata
</div>

PracticalCourses/Views/Home/Community.cshtml
@{
    ViewData["Title"] = "Community";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Community</h2>

<div>
    Possim vulputate takimata ex tempor consetetur diam duis et eos duo labore dolores voluptua magna vulputate at duo takimata dolore erat accusam
    sed est erat elitr at consetetur augue eleifend diam dolor dolores voluptua nonumy amet takimata et ut amet sea sit dolores feugait adipiscing volutpat
    magna molestie est dolores takimata te consequat eirmod et justo sadipscing lorem magna nostrud luptatum dolore duis diam sit duis duo sed tempor qui sit lorem
    at takimata at ad justo vero ut illum clita at diam elit in illum diam sanctus sanctus dolor ipsum nisl dignissim nulla ut te amet amet at eirmod
    Amet diam ea ea lorem ipsum magna sea kasd facilisis duis justo gubergren nonumy dolores dolor elitr tempor eum aliquyam ut nonumy volutpat labore ut ipsum ut
    ipsum vero dolor at vero erat dolores dolore nonumy sadipscing ipsum nonummy est ea dolore duo delenit nonumy labore invidunt adipiscing et kasd duo adipiscing
    lorem volutpat nobis te lorem ad labore dolor et et ipsum sea augue in nulla amet sea clita ipsum dolore facer diam dolore et ut accusam amet dolor eum et sit stet
    duo magna et kasd et hendrerit qui exerci accusam nibh lorem ut vel consetetur sit eos
    At et ut labore clita dolor sed no sanctus diam lorem zzril odio dolore vero lorem magna sed sed ut et augue labore lorem dolore suscipit zzril kasd liber
    elitr voluptua sit accusam eum diam sea et cum ex et diam nobis est eirmod sit lorem diam eirmod aliquyam est eirmod nam et nisl gubergren clita invidunt
    ut placerat voluptua dolore aliquyam odio ea dolor nonummy dolor sed lorem rebum et dolore nulla et et vel takimata sit lorem facilisi et diam facer nobis laoreet
    eirmod et velit commodo ea at dolore stet at eirmod kasd aliquyam sed tempor takimata
    Possim vulputate takimata ex tempor consetetur diam duis et eos duo labore dolores voluptua magna vulputate at duo takimata dolore erat accusam
    sed est erat elitr at consetetur augue eleifend diam dolor dolores voluptua nonumy amet takimata et ut amet sea sit dolores feugait adipiscing volutpat
    magna molestie est dolores takimata te consequat eirmod et justo sadipscing lorem magna nostrud luptatum dolore duis diam sit duis duo sed tempor qui sit lorem
    at takimata at ad justo vero ut illum clita at diam elit in illum diam sanctus sanctus dolor ipsum nisl dignissim nulla ut te amet amet at eirmod
    Amet diam ea ea lorem ipsum magna sea kasd facilisis duis justo gubergren nonumy dolores dolor elitr tempor eum aliquyam ut nonumy volutpat labore ut ipsum ut
    ipsum vero dolor at vero erat dolores dolore nonumy sadipscing ipsum nonummy est ea dolore duo delenit nonumy labore invidunt adipiscing et kasd duo adipiscing
    lorem volutpat nobis te lorem ad labore dolor et et ipsum sea augue in nulla amet sea clita ipsum dolore facer diam dolore et ut accusam amet dolor eum et sit stet
    duo magna et kasd et hendrerit qui exerci accusam nibh lorem ut vel consetetur sit eos
    At et ut labore clita dolor sed no sanctus diam lorem zzril odio dolore vero lorem magna sed sed ut et augue labore lorem dolore suscipit zzril kasd liber
    elitr voluptua sit accusam eum diam sea et cum ex et diam nobis est eirmod sit lorem diam eirmod aliquyam est eirmod nam et nisl gubergren clita invidunt
    ut placerat voluptua dolore aliquyam odio ea dolor nonummy dolor sed lorem rebum et dolore nulla et et vel takimata sit lorem facilisi et diam facer nobis laoreet
    eirmod et velit com
</div>

PracticalCourses/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Contact</h2>

<div>
    Possim vulputate takimata ex tempor consetetur diam duis et eos duo labore dolores voluptua magna vulputate at duo takimata dolore erat accusam
    sed est erat elitr at consetetur augue eleifend diam dolor dolores voluptua nonumy amet takimata et ut amet sea sit dolores feugait adipiscing volutpat
    magna molestie est dolores takimata te consequat eirmod et justo sadipscing lorem magna nostrud luptatum dolore duis diam sit duis duo sed tempor qui sit lorem
    at takimata at ad justo vero ut illum clita at diam elit in illum diam sanctus sanctus dolor ipsum nisl dignissim nulla ut te amet amet at eirmod
    Amet diam ea ea lorem ipsum magna sea kasd facilisis duis justo gubergren nonumy dolores dolor elitr tempor eum aliquyam ut nonumy volutpat labore ut ipsum ut
    ipsum vero dolor at vero erat dolores dolore nonumy sadipscing ipsum nonummy est ea dolore duo delenit nonumy labore invidunt adipiscing et kasd duo adipiscing
    lorem volutpat nobis te lorem ad labore dolor et et ipsum sea augue in nulla amet sea clita ipsum dolore facer diam dolore et ut accusam amet dolor eum et sit stet
    duo magna et kasd e
</div>

PracticalCourses/Views/Home/Feedbacks.cshtml
@{
    ViewData["Title"] = "Feedbacks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Feedbacks</h2>

<div>
    Possim vulputate takimata ex tempor consetetur diam duis et eos duo labore dolores voluptua magna vulputate at duo takimata dolore erat accusam
    sed est erat elitr at consetetur augue eleifend diam dolor dolores voluptua nonumy amet takimata et ut amet sea sit dolores feugait adipiscing volutpat
    magna molestie est dolores takimata te consequat eirmod et justo sadipscing lorem magna nostrud luptatum dolore duis diam sit duis duo sed tempor qui sit lorem
    at takimata at ad justo vero ut illum clita at diam elit in illum diam sanctus sanctus dolor ipsum nisl dignissim nulla ut te amet amet at eirmod
    Amet diam ea ea lorem ipsum magna sea kasd facilisis duis justo gubergren nonumy dolores dolor elitr tempor eum aliquyam ut nonumy volutpat labore ut ipsum ut
    ipsum vero dolor at vero erat dolores dolore nonumy sadipscing ipsum nonummy est ea dolore duo delenit nonumy labore invidunt adipiscing et kasd duo adipiscing
    lorem volutpat nobis te lorem ad labore dolor et et ipsum sea augue in nulla amet sea clita ipsum dolore facer diam dolore et ut accusam amet dolor eum et sit stet
    duo magna et kasd et hendrerit qui exerci accusam nibh lorem ut vel consetetur sit eos
    At et ut labore clita dolor sed no sanctus diam lorem zzril odio dolore vero lorem magna sed sed ut et augue labore lorem dolore suscipit zzril kasd liber
    elitr voluptua sit accusam eum diam sea et cum ex et diam nobis est eirmod sit lorem diam eirmod aliquyam est eirmod nam et nisl gubergren clita invidunt
    ut placerat voluptua dolore aliquyam odio ea dolor nonummy dolor sed lorem rebum et dolore nulla et et vel takimata sit lorem facilisi et diam facer nobis laoreet
    eirmod et velit com
    Possim vulputate takimata ex tempor consetetur diam duis et eos duo labore dolores voluptua magna vulputate at duo takimata dolore erat accusam
    sed est erat elitr at consetetur augue eleifend diam dolor dolores voluptua nonumy amet takimata et ut amet sea sit dolores feugait adipiscing volutpat
    magna molestie est dolores takimata te consequat eirmod et justo sadipscing lorem magna nostrud luptatum dolore duis diam sit duis duo sed tempor qui sit lorem
    at takimata at ad justo vero ut illum clita at diam elit in illum diam sanctus sanctus dolor ipsum nisl dignissim nulla ut te amet amet at eirmod
    Amet diam ea ea lorem ipsum magna sea kasd facilisis duis justo gubergren nonumy dolores dolor elitr tempor eum aliquyam ut nonumy volutpat labore ut ipsum ut
    ipsum vero dolor at vero erat dolores dolore nonumy sadipscing ipsum nonummy est ea dolore duo delenit nonumy labore invidunt adipiscing et kasd duo adipiscing
    lorem volutpat nobis te lorem ad labore dolor et et ipsum sea augue in nulla amet sea clita ipsum dolore facer diam dolore et ut accusam amet dolor eum et sit stet
    duo magna et kasd et hendrerit qui exerci accusam nibh lorem ut vel consetetur sit eos
    At et ut labore clita dolor sed no sanctus diam lorem zzril odio dolore vero lorem magna sed sed ut et augue labore lorem dolore suscipit zzril kasd liber
    elitr voluptua sit accusam eum diam sea et cum ex et diam nobis est eirmod sit lorem diam eirmod aliquyam est eirmod nam et nisl gubergren clita invidunt
    ut placerat voluptua dolore aliquyam odio ea dolor nonummy dolor sed lorem rebum et dolore nulla et et vel takimata sit lorem facilisi et diam facer nobis laoreet
    eirmod et velit com
    Possim vulputate takimata ex tempor consetetur diam duis et eos duo labore dolores voluptua magna vulputate at duo takimata dolore erat accusam
    sed est erat elitr at consetetur augue eleifend diam dolor dolores voluptua nonumy amet takimata et ut amet sea sit dolores feugait adipiscing volutpat
    magna molestie est dolores takimata te consequat eirmod et justo sadipscing lorem magna nostrud luptatum dolore duis diam sit duis duo sed tempor qui sit lorem
    at takimata at ad justo vero ut illum clita at diam elit in illum diam sanctus sanctus dolor ipsum nisl dignissim nulla ut te amet amet at eirmod
    Amet diam ea ea lorem ipsum magna sea kasd facilisis duis justo gubergren nonumy dolores dolor elitr tempor eum aliquyam ut nonumy volutpat labore ut ipsum ut
    ipsum vero dolor at vero erat dolores dolore nonumy sadipscing ipsum nonummy est ea dolore duo delenit nonumy labore invidunt adipiscing et kasd duo adipiscing
    lorem volutpat nobis te lorem ad labore dolor et et ipsum sea augue in nulla amet sea clita ipsum dolore facer diam dolore et ut accusam amet dolor eum et sit stet
    duo magna et kasd et hendrerit qui exerci accusam nibh lorem ut vel consetetur sit eos
    At et ut labore clita dolor sed no sanctus diam lorem zzril odio dolore vero lorem magna sed sed ut et augue labore lorem dolore suscipit zzril kasd liber
    elitr voluptua sit accusam eum diam sea et cum ex et diam nobis est eirmod sit lorem diam eirmod aliquyam est eirmod nam et nisl gubergren clita invidunt
    ut placerat voluptua dolore aliquyam odio ea dolor nonummy dolor sed lorem rebum et dolore nulla et et vel takimata sit lorem facilisi et diam facer nobis laoreet
    eirmod et velit com
</div>

PracticalCourses/Views/Home/Help.cshtml
@{
    ViewData["Title"] = "Help";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Help</h2>

<div>
    Possim vulputate takimata ex tempor consetetur diam duis et eos duo labore dolores voluptua magna vulputate at duo takimata dolore erat accusam
    sed est erat elitr at consetetur augue eleifend diam dolor dolores voluptua nonumy amet takimata et ut amet sea sit dolores feugait adipiscing volutpat
    magna molestie est dolores takimata te consequat eirmod et justo sadipscing lorem magna nostrud luptatum dolore duis diam sit duis duo sed tempor qui sit lorem
    at takimata at ad justo vero ut illum clita at diam elit in illum diam sanctus sanctus dolor ipsum nisl dignissim nulla ut te amet amet at eirmod
    Amet diam ea ea lorem ipsum magna sea kasd facilisis duis justo gubergren nonumy dolores dolor elitr tempor eum aliquyam ut nonumy volutpat labore ut ipsum ut
    ipsum vero dolor at vero erat dolores dolore nonumy sadipscing ipsum nonummy est ea dolore duo delenit nonumy labore invidunt adipiscing et kasd duo adipiscing
    lorem volutpat nobis te lorem ad labore dolor et et ipsum sea augue in nulla amet sea clita ipsum dolore facer diam dolore et ut accusam amet dolor eum et sit stet
    duo magna et kasd et hendrerit qui exerci accusam nibh lorem ut vel consetetur sit eos
    At et ut labore clita dolor sed no sanctus diam lorem zzril odio dolore vero lorem magna sed sed ut et augue labore lorem dolore suscipit zzril kasd liber
    elitr voluptua sit accusam eum diam sea et cum ex et diam nobis est eirmod sit lorem diam eirmod aliquyam est eirmod nam et nisl gubergren clita invidunt
    ut placerat voluptua dolore aliquyam odio ea dolor nonummy dolor sed lorem rebum et dolore nulla et et vel takimata sit lorem facilisi et diam facer nobis laoreet
    eirmod et velit com Possim vulputate takimata ex tempor consetetur diam duis et eos duo labore dolores voluptua magna vulputate at duo takimata dolore erat accusam
    sed est erat elitr at consetetur augue eleifend diam dolor dolores voluptua nonumy amet takimata et ut amet sea sit dolores feugait adipiscing volutpat
    magna molestie est dolores takimata te consequat eirmod et justo sadipscing lorem magna nostrud luptatum dolore duis diam sit duis duo sed tempor qui sit lorem
    at takimata at ad justo vero ut illum clita at diam elit in illum diam sanctus sanctus dolor ipsum nisl dignissim nulla ut te amet amet at eirmod
    Amet diam ea ea lorem ipsum magna sea kasd facilisis duis justo gubergren nonumy dolores dolor elitr tempor eum aliquyam ut nonumy volutpat labore ut ipsum ut
    ipsum vero dolor at vero erat dolores dolore nonumy sadipscing ipsum nonummy est ea dolore duo delenit nonumy labore invidunt adipiscing et kasd duo adipiscing
    lorem volutpat nobis te lorem ad labore dolor et et ipsum sea augue in nulla amet sea clita ipsum dolore facer diam dolore et ut accusam amet dolor eum et sit stet
    duo magna et kasd et hendrerit qui exerci accusam nibh lorem ut vel consetetur sit eos
    At et ut labore cli
</div>

PracticalCourses/Views/Home/Index.cshtml
@model PracticalCourses.ViewModel.HomeIndexViewModel
@using PracticalCourses.Infrastructure

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Praktyczne kursy";
}

<nav class="kategorieHorizontal">
    <ul>
        @foreach (var category in Model.Categories)
        {
            <li>
                <a href="@Url.Action("List","Course", new { nameCategory= category.NameCategory.ToLower()})" 
                   style="background-image: url(@Url.PathToImagesCategories(category.NameFileIcon));">
                    @category.NameCategory
                </a>
            </li>
        }
    </ul>

    <a href="link">
        <img id="baner" src="@Url.Content("~/images/baner.png")" />
    </a>
</nav>

<section>
    <ul class="KursyTrzyKolumny duzaListaKursy">
        @foreach (var bestseller in Model.Bestsellers)
        {
            <li>
                <article>
                    <a class="dodajDoKoszykaLink" href="@Url.Action("AddToBasket","Basket", new { id=bestseller.CourseId})">
                        <img src="@Url.Content("~/images/koszyk.png")" />
                    </a>
                    <a class="kursSzczegolyLink" href="@Url.Action("Details","Course", new { courseId = bestseller.CourseId})">
                        <div class="bestsellerFlag"><img src="~/images/new.png" /></div>
                        <img class="kurs" src="@Url.PathToImagesCourses(bestseller.NameFileImage)" />
                        <h1>
                            @bestseller.TitleCourse - @bestseller.AuthorCourse
                        </h1>
                    </a>
                </article>
            </li>
        }
    </ul>
</section>

<section>
    <ul class="KursyTrzyKolumny duzaListaKursy">
        @foreach (var news in Model.News)
        {
            <li>
                <article>
                    <a class="dodajDoKoszykaLink" href="@Url.Action("AddToBasket", "Basket", new { id=news.CourseId})">
                        <img src="@Url.Content("~/images/koszyk.png")" />
                    </a>
                    <a class="kursSzczegolyLink" href="@Url.Action("Details","Course", new { courseId=news.CourseId})">
                        <div class="newFlag"><img src="@Url.Content("~/images/bestseller.png")"/></div>
                        <img class="kurs" src="@Url.PathToImagesCourses(news.NameFileImage)" />
                        <h1>
                            @news.TitleCourse - @news.AuthorCourse
                        </h1>
                    </a>
                </article>
            </li>
        }
    </ul>
</section>