PracticalCourses/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PracticalCourses.Controllers
{
    public class BasketController : Controller
    {
        public IActionResult AddToBasket(string id)
        {
            return View();
        }
    }
}

PracticalCourses/Controllers/CourseController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PracticalCourses.Interfaces;
using PracticalCourses.Models;

namespace PracticalCourses.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly ICourseService _courseService;

        public CourseController(ICategoryService categoryService, ICourseService courseService)
        {
            _categoryService = categoryService;
            _courseService = courseService;
        }
        
        [HttpGet]
        [Route("Kategoria/{nameCategory}")]
        public IActionResult List(string nameCategory)
        {
            ViewBag.NameCategory = nameCategory;

            return View();
        }
        
        [HttpGet]
        [Route("kurs-{courseId}.html")]
        public IActionResult Details(int courseId)
        {
            return View(AutoMapper.Mapper.Map<CourseResponse>(_courseService.GetById(courseId)));
        }
    }
}

PracticalCourses/ViewComponents/CoursesListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PracticalCourses.Interfaces;
using PracticalCourses.Models;
using PracticalCourses.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PracticalCourses.ViewComponents
{
    public class CoursesListViewComponent : ViewComponent
    {
        private readonly ICourseService _courseService;

        public CoursesListViewComponent(ICourseService courseService)
        {
            _courseService = courseService;
        }

        public async Task<IViewComponentResult> InvokeAsync(string nameCategory)
        {
            var courses = AutoMapper.Mapper.Map<List<CourseResponse>>(await _courseService.GetByCourseId(nameCategory));

            return View("_CoursesList", courses);
        }
    }
}

PracticalCourses/ViewComponents/MenuCategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PracticalCourses.Interfaces;
using PracticalCourses.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PracticalCourses.ViewComponents
{
    public class MenuCategoriesViewComponent : ViewComponent
    {
        private readonly ICategoryService _categoryService;

        public MenuCategoriesViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = AutoMapper.Mapper.Map<List<CategoryResponse>>(await _categoryService.GetAllCategory());

            return View("_MenuCategories", categories);
        }
    }
}

PracticalCourses/Views/Course/Details.cshtml
@model PracticalCourses.Models.CourseResponse
@using PracticalCourses.Infrastructure

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="ListaKategoriZawartosc">
   
    @await  Component.InvokeAsync("MenuCategories")

    <div id="KategorieListPrawaSekcja">
        <div id="Breadcrumb">
            <img src="@Url.Content("~/images/dommaly.png")" />
            <a href="link">
                Start > ASP.NET
            </a>
        </div>
        <section id="SekcjaKurs">
            <div id="KursLewa">
                <img src="@Url.PathToImagesCourses(Model.NameFileImage)" />
            </div>
            <div id="KursPrawa">
                <div id="KursNazwa">
                    <h1>
                        @Model.TitleCourse
                    </h1>
                    <h2>
                        @Model.AuthorCourse
                    </h2>
                </div>
                <div id="KursCena">
                    <div>
                        @string.Format("{0:0.##}", Model.PriceCourse)<span>PLN</span>
                    </div>
                    <a href="@Url.Action("AddToBasket", "Basket", new { id=Model.CourseId})"></a>
                </div>
                <div id="KursOpis">
                    @Model.DescriptionCourse
                </div>
                <div id="KursInfo">
                   @Model.ShortDescriptionCourse
                </div>

            </div>
        </section>
    </div>
</div>

PracticalCourses/Views/Course/List.cshtml
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="ListaKategoriZawartosc">
    @await Component.InvokeAsync("MenuCategories")

    <div id="KategorieListPrawaSekcja">
        <div id="Breadcrumb">
            <img src="@Url.Content("~/images/dommaly.png")" />
            <a href="link">
                Start > ASP.NET
            </a>
        </div>

            @await Component.InvokeAsync("CoursesList", new { nameCategory = ViewBag.NameCategory })
   
    </div>
</div>